/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author 1hematilldyl
 */
public class game2048 extends javax.swing.JFrame {
    
    int score = 0;
    JLabel[][] boxes = new JLabel[4][4];
    int[][] values = new int[4][4];
    boolean gameWon = false;
    
    static{
        Color[] colours = {
        new Color(60, 186, 84)
            
        };
                }
    
    
    /**
     * Creates new form game2048
     */
    public game2048() {
        initComponents();
        
        boxes[0][0]= box00;
        boxes[0][1]= box10;
        boxes[0][2]= box20;
        boxes[0][3]= box30;
        
        boxes[1][0]= box01;
        boxes[1][1]= box11;
        boxes[1][2]= box21;
        boxes[1][3]= box31;
        
        boxes[2][0] = box02;
        boxes[2][1] = box12;
        boxes[2][2] = box22;
        boxes[2][3] = box32;
        
        boxes[3][0] = box03;
        boxes[3][1] = box13;
        boxes[3][2] = box23;
        boxes[3][3] = box33;
        
        //FirstTWO
        placeRandomTwo();
         placeRandomTwo();
         
         //update display
        updateDisplay();
         
    }
        private void updateDisplay(){
            for(int r = 0; r < values.length; r++){
                for(int c = 0; c < values[r].length; c++){
                    if(values[r][c] == 0){
                    boxes[r][c].setText("");
                }else{
                   boxes[r][c].setText(values[r][c] + "");
                    }
                }
            }
            point.setText("" + score);
            
            //Colour
            
}
    private void placeRandomTwo(){
        int r, c;
        boolean placed = false;
        do{
        r = (int)(Math.random()*4);
        c = (int)(Math.random()*4);
        
        //EMPTY!
        if(values[r][c] == 0){
           values[r][c] =2;
           placed = true;
        }
        }while(!placed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        box00 = new javax.swing.JLabel();
        box10 = new javax.swing.JLabel();
        box20 = new javax.swing.JLabel();
        box30 = new javax.swing.JLabel();
        box01 = new javax.swing.JLabel();
        box11 = new javax.swing.JLabel();
        box21 = new javax.swing.JLabel();
        box31 = new javax.swing.JLabel();
        box02 = new javax.swing.JLabel();
        box12 = new javax.swing.JLabel();
        box22 = new javax.swing.JLabel();
        box32 = new javax.swing.JLabel();
        box03 = new javax.swing.JLabel();
        box13 = new javax.swing.JLabel();
        box23 = new javax.swing.JLabel();
        box33 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        point = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 153));

        box00.setBackground(new java.awt.Color(255, 153, 153));
        box00.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box00.setForeground(new java.awt.Color(255, 51, 51));
        box00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box00.setText("2");
        box00.setOpaque(true);

        box10.setBackground(new java.awt.Color(255, 153, 153));
        box10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box10.setForeground(new java.awt.Color(255, 51, 51));
        box10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box10.setText("2");
        box10.setOpaque(true);

        box20.setBackground(new java.awt.Color(255, 153, 153));
        box20.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box20.setForeground(new java.awt.Color(255, 51, 51));
        box20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box20.setText("2");
        box20.setOpaque(true);

        box30.setBackground(new java.awt.Color(255, 153, 153));
        box30.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box30.setForeground(new java.awt.Color(255, 51, 51));
        box30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box30.setText("2");
        box30.setOpaque(true);

        box01.setBackground(new java.awt.Color(255, 153, 153));
        box01.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box01.setForeground(new java.awt.Color(255, 51, 51));
        box01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box01.setText("2");
        box01.setOpaque(true);

        box11.setBackground(new java.awt.Color(255, 153, 153));
        box11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box11.setForeground(new java.awt.Color(255, 51, 51));
        box11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box11.setText("2");
        box11.setOpaque(true);

        box21.setBackground(new java.awt.Color(255, 153, 153));
        box21.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box21.setForeground(new java.awt.Color(255, 51, 51));
        box21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box21.setText("2");
        box21.setOpaque(true);

        box31.setBackground(new java.awt.Color(255, 153, 153));
        box31.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box31.setForeground(new java.awt.Color(255, 51, 51));
        box31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box31.setText("2");
        box31.setOpaque(true);

        box02.setBackground(new java.awt.Color(255, 153, 153));
        box02.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box02.setForeground(new java.awt.Color(255, 51, 51));
        box02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box02.setText("2");
        box02.setOpaque(true);

        box12.setBackground(new java.awt.Color(255, 153, 153));
        box12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box12.setForeground(new java.awt.Color(255, 51, 51));
        box12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box12.setText("2");
        box12.setOpaque(true);

        box22.setBackground(new java.awt.Color(255, 153, 153));
        box22.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box22.setForeground(new java.awt.Color(255, 51, 51));
        box22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box22.setText("2");
        box22.setOpaque(true);

        box32.setBackground(new java.awt.Color(255, 153, 153));
        box32.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box32.setForeground(new java.awt.Color(255, 51, 51));
        box32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box32.setText("2");
        box32.setOpaque(true);

        box03.setBackground(new java.awt.Color(255, 153, 153));
        box03.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box03.setForeground(new java.awt.Color(255, 51, 51));
        box03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box03.setText("2");
        box03.setOpaque(true);

        box13.setBackground(new java.awt.Color(255, 153, 153));
        box13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box13.setForeground(new java.awt.Color(255, 51, 51));
        box13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box13.setText("2");
        box13.setOpaque(true);

        box23.setBackground(new java.awt.Color(255, 153, 153));
        box23.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box23.setForeground(new java.awt.Color(255, 51, 51));
        box23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box23.setText("2");
        box23.setOpaque(true);

        box33.setBackground(new java.awt.Color(255, 153, 153));
        box33.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        box33.setForeground(new java.awt.Color(255, 51, 51));
        box33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box33.setText("2");
        box33.setOpaque(true);

        jButton1.setText("Right");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        point.setText("jLabel2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(box00, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box30, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(box01, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box21, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box31, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(box02, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box22, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box32, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(box03, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box23, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box33, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(point)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box00, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box30, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box01, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box31, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box02, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box32, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box03, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box33, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(3, 3, 3)
                .addComponent(point))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
                shiftRight();
                mergeRight();
                shiftRight();
                placeRandomTwo();
                updateDisplay();
               
        //mergeRight();
        // shiftRight();

    }//GEN-LAST:event_jButton1ActionPerformed
  private void shiftRight(){
          //for Rows
        for (int r = 0; r < values.length; r++) {
            for (int pass = 0; pass < values[r].length - 1; pass++) {
                //look left
                for (int c = 0; c < values[r].length - 1 - pass; c++) {
                    if (values[r][c + 1] == 0) {
                        values[r][c + 1] = values[r][c];
                        values[r][c] = 0;
                       
  }
    
        
                }  
            }
        }
  }
  
  private void mergeRight(){
        //for Rows
        for (int r = 0; r < values.length; r++) {
            for (int pass = 0; pass < values[r].length - 1; pass++) {
                //look left
                for (int c = values[r].length-1; c>0; c--) {
                    if (values[r][c] == values[r][c -1]) {
                        values[r][c] = values[r][c] * 2; 
                        values[r][c -1] = 0;
                        score = score + values[r][c];
                        if(values[r][c] == 2048){
                            gameWon = true;
                        }
                    }
                }
            }
        }
  
  }
  
  private void gameOver(){
      
  }
   // }
    /**a
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game2048.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game2048().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel box00;
    private javax.swing.JLabel box01;
    private javax.swing.JLabel box02;
    private javax.swing.JLabel box03;
    private javax.swing.JLabel box10;
    private javax.swing.JLabel box11;
    private javax.swing.JLabel box12;
    private javax.swing.JLabel box13;
    private javax.swing.JLabel box20;
    private javax.swing.JLabel box21;
    private javax.swing.JLabel box22;
    private javax.swing.JLabel box23;
    private javax.swing.JLabel box30;
    private javax.swing.JLabel box31;
    private javax.swing.JLabel box32;
    private javax.swing.JLabel box33;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel point;
    // End of variables declaration//GEN-END:variables
}
